[delta]
  syntax-theme = gruvbox-material-light
  minus-style = "syntax #f9e0bb"
  minus-emph-style = "syntax #f1d9b5"
  zero-style = "syntax auto"
  plus-style = "syntax #e6eabc"
  plus-emph-style = "syntax #dee2b6"
  line-numbers-minus-style = "#c14a4a auto"
  line-numbers-zero-style = "#928374 auto"
  line-numbers-left-style = "#928374 auto"
  line-numbers-plus-style = "#6c782e auto"
  hunk-header-decoration-style = "#45707a box"
