[delta]
  syntax-theme = gruvbox-material-dark
  minus-style = "syntax #402120"
  minus-emph-style = "syntax #4c3432"
  zero-style = "syntax auto"
  plus-style = "syntax #34381b"
  plus-emph-style = "syntax #3b4439"
  line-numbers-minus-style = "#ea6962 auto"
  line-numbers-zero-style = "#928374 auto"
  line-numbers-left-style = "#928374 auto"
  line-numbers-plus-style = "#a9b665 auto"
  hunk-header-decoration-style = "#7daea3 box"
