#!/bin/bash

# Variables
SOURCE_FOLDER="$HOME/Music"
DEST_FOLDER="${SOURCE_FOLDER}_temp"
PYTHON_SCRIPT="${DEST_FOLDER}/scripts/sanitize_files_and_folders.py"
# no need to "--exclude scripts --delete-excluded" in ADB_COMMAND because adbsync ignores symlinks by default
ADB_COMMAND="adbsync --del --show-progress push ${DEST_FOLDER}/ /sdcard/Music"

# Check if the source folder exists
if [ ! -d "$SOURCE_FOLDER" ]; then
  echo -e "\nError: Source folder does not exist.\n"
  exit 1
fi

# 1. Copy the folder
echo -e "\nCopying the folder ..."
cp -pr "$SOURCE_FOLDER" "$DEST_FOLDER"

# 1.1 Remove the .song_ids files generated by zotify, if they exist
echo -e "\nRemoving .song_ids files ..."
find "$DEST_FOLDER" -name ".song_ids" -type f -delete

# Check if the copy was successful
if [ $? -ne 0 ]; then
  echo -e "\nError: Failed to copy the folder."
  exit 1
fi

# 2. Run the Python script
echo -e "\nRenaming invalid files and folders ...\n"
python "$PYTHON_SCRIPT" "$DEST_FOLDER"

# Check if the Python script ran successfully
if [ $? -ne 0 ]; then
  echo -e "\nError: Python script failed. Removing $DEST_FOLDER ...\n"
  rm -rf "$DEST_FOLDER"
  exit 1
fi

# 3. Run the ADB command

## 3.1 Move thumbnails cache so it's not deleted by adbsync
echo -e "\nMoving thumbnails cache ...\n"
adb shell mv /sdcard/Music/.thumbnails /sdcard/

## 3.2 Run the ADB command
$ADB_COMMAND

## 3.3 Move thumbnails cache back
echo -e "\nMoving thumbnails cache back ..."
adb shell mv /sdcard/.thumbnails /sdcard/Music/

# Check if the ADB command ran successfully
if [ $? -ne 0 ]; then
  echo -e "\nError: adbsync command failed. Removing $DEST_FOLDER ...\n"
  rm -rf "$DEST_FOLDER"
  exit 1
fi

# 4. Remove the folder
echo -e "\nRemoving $DEST_FOLDER ..."
rm -rf "$DEST_FOLDER"

# Check if the folder was removed successfully
if [ $? -ne 0 ]; then
  echo -e "\nError: Failed to remove the folder."
  exit 1
fi

echo -e "\nScript completed successfully!"
