git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --side-by-side
gui:
  sidePanelWidth: 0.3333
  nerdFontsVersion: "3"
promptToReturnFromSubprocess: false
notARepository: "skip"
