# Theme
import = [ "~/.config/alacritty/tokyonight_moon.toml" ]

shell = "/bin/zsh"
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.90
blur = true
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "None"
decorations_theme_variant = "Dark"
dimensions = { columns = 180, lines = 46 }

[font]
normal = { family = "JetBrains Mono", style = "Light" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Light Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 14.8
builtin_box_drawing = false

[scrolling]
history = 15000

[terminal]
osc52 = "OnlyCopy"

[selection]
save_to_clipboard = true

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
	{ key = "C", mods = "Control|Shift", action = "Copy" },
	{ key = "V", mods = "Control|Shift", action = "Paste" },
	{ key = "Enter", mods = "Control|Shift", action = "SpawnNewInstance" },
	{ key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
	# remove alacritty search
	{ key = "F", mods = "Control|Shift", action = "ReceiveChar" },
]
